meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: elasticsearch_plugins_leader_z1
    templates:
    - name: elasticsearch-plugins
      release: elasticsearch-plugins
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties: {}
  - name: elasticsearch_plugins_z1
    templates:
    - name: elasticsearch-plugins
      release: elasticsearch-plugins
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      elasticsearch_plugins:
        leader_address: (( merge ))

networks: (( merge ))

properties: {}
